### ISSUE TITLE
Question: How do the errors get rendered if the create fails?

### ISSUE THREAD

**Issue by enricribas** [christophgockel/rail-track#1]
In the controller, the Validation Object now controls the errors, but when you render :new again after failing, none of the fields will be marked with errors, correct? Sure you have the messages as a flash, and you have an @movie object, but you now miss the actual errors on that object. Maybe I missed something?

**Comment by digaev** [comment]
I have the same question, and I think it is possible to use `@movie.errors` instead of `@messages` in `Movies::Validator` or `Movies::Validator::Result`.
